version: '2'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - ./volumes/zookeper-persistence:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    hostname: localhost
    ports:
      - '9092:9092'
    volumes:
      - ./volumes/kafka-persistence:/bitnami/kafka
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

networks:
  kafka-network:
    driver: bridge
    external: true
